stage/auth_gateway/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = "AuthGateway"
urlpatterns = [
    path("validerconnexion/", validerconnexion, name="validerconnexion"),
    path("validerinscription/", validerinscription, name="validerinscription"),
    path("logout/", deconnexion, name="logout"),

]

stage/stage/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index),
    path("apropos/", apropos, name="apropos"),
    path("contact/", contact, name="contact"),
    path("inscription/", inscription, name="inscription"),
    path("connexion/", connexion, name="connexion"),
    path("profil/", profil, name="profil"),
    path("categories/", categories, name="categories"),
    path("produits/", produits, name="produits"),
    path("produits/<int:id>/", produit, name="produit-detail"),
    path("auth/", include("auth_gateway.urls")),
    path("panier/", panier, name="panier"),
    path("viderpanier/", viderpanier, name="viderpanier"),
    path("validerajoutpanier/", validerajoutpanier, name="validerajoutpanier"),
    path("procederpaiement/", procederpaiement, name="procederpaiement"),
    path("procederpaiement/webhook/", procederpaiementwebhook, name="procederpaiementwebhook"),    
    path("paiementannuler/", paiementannuler, name="paiementannuler"),
    path("paiementeffectuer/", paiementeffectuer, name="paiementeffectuer"),

    
]

stage/templates/apropos.html
{% extends './layouts/base.html' %}
{% load static %}
{% block title %}
Apropos
{% endblock %}

{% block content %}
<!-- Title page -->
<section class="bg-img1 txt-center p-lr-15 p-tb-92" style="background-image: url({% static 'images/bg-01.jpg' %});">
    <h2 class="ltext-105 cl0 txt-center">
        A Propos
    </h2>
</section>
<!-- Content page -->
<section class="bg0 p-t-75 p-b-120">
    <div class="container">
        <div class="row p-b-148">
            <div class="col-md-7 col-lg-8">
                <div class="p-t-7 p-r-85 p-r-15-lg p-r-0-md">
                    <h3 class="mtext-111 cl2 p-b-16">
                        Notre Histoire
                    </h3>

                    <p class="stext-113 cl6 p-b-26">
                        Bienvenue chez L&H, votre destination de choix pour des produits de qualité. Fondée avec passion, notre entreprise a pour mission de vous offrir une expérience d'achat unique et agréable. Chez L&H, nous croyons en l'importance de l'excellence et du service client. Nous nous efforçons de sélectionner les meilleurs produits pour répondre à vos besoins et surpasser vos attentes.
                    </p>

                    <p class="stext-113 cl6 p-b-26">
                        Depuis notre création, nous avons évolué en restant fidèles à nos valeurs fondamentales : intégrité, innovation et engagement envers nos clients. Nous sommes fiers de notre parcours et des relations durables que nous avons établies avec nos clients et partenaires.
                    </p>

                    <p class="stext-113 cl6 p-b-26">
                        Si vous avez des questions, n'hésitez pas à nous contacter en magasin au 8ème étage, 379 Hudson St, New York, NY 10018 ou appelez-nous au (+1) 96 716 6879. Nous sommes impatients de vous servir et de vous aider à trouver exactement ce que vous cherchez.
                    </p>
                </div>
            </div>

            <div class="col-11 col-md-5 col-lg-4 m-lr-auto">
                <div class="how-bor1 ">
                    <div class="hov-img0">
                        <img src="{% static "images/about-01.jpg" %}" alt="IMG">
                    </div>
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="order-md-2 col-md-7 col-lg-8 p-b-30">
                <div class="p-t-7 p-l-85 p-l-15-lg p-l-0-md">
                    <h3 class="mtext-111 cl2 p-b-16">
                        Notre Mission
                    </h3>
                
                    <p class="stext-113 cl6 p-b-26">
                        Chez L&H, notre mission est de fournir des produits de qualité exceptionnelle tout en garantissant une expérience d'achat inégalée. Nous nous engageons à offrir à nos clients un service personnalisé et attentif, répondant à leurs besoins et attentes avec précision et souci du détail. Notre objectif est de créer un environnement où chaque client se sent valorisé et satisfait de ses achats.
                    </p>
                
                    <p class="stext-113 cl6 p-b-26">
                        Nous croyons fermement en l'innovation continue et en l'amélioration constante de nos processus et de notre gamme de produits. Nous nous efforçons de rester à la pointe des tendances et des technologies pour vous offrir les meilleures solutions possibles. Chez L&H, nous sommes dévoués à bâtir une relation de confiance avec nos clients, basée sur la transparence, l'intégrité et la qualité.
                    </p>
                
                    <div class="bor16 p-l-29 p-b-9 m-t-22">
                        <p class="stext-114 cl6 p-r-40 p-b-11">
                            "La créativité, c'est simplement relier les choses. Lorsque vous demandez à des personnes créatives comment elles ont fait quelque chose, elles se sentent un peu coupables parce qu'elles ne l'ont pas vraiment fait, elles ont juste vu quelque chose. Cela leur semblait évident après un certain temps."
                        </p>
                    </div>
                </div>
                
            </div>

            <div class="order-md-1 col-11 col-md-5 col-lg-4 m-lr-auto p-b-30">
                <div class="how-bor2">
                    <div class="hov-img0">
                        <img src="{% static "images/about-02.jpg" %}" alt="IMG">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>	


{% endblock %}

{% block scripts %}
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

{% endblock %}

stage/templates/categories.html
{% extends './layouts/base.html' %}
{% load static %}
{% block title %}
Categories
{% endblock %}

{% block content %}
<!-- Title page -->
<section class="bg-img1 txt-center p-lr-15 p-tb-92" style="background-image: url({% static 'images/bg-01.jpg' %});">
    <h2 class="ltext-105 cl0 txt-center">
        Catégories De Produits
    </h2>
</section>


<!-- Banner -->
<div class="sec-banner bg0 p-t-80 p-b-50">
    <div class="container">
        <div class="row">

            {% for categorie in categories %}
            <div class="col-md-6 col-xl-4 p-b-30 m-lr-auto">
                <div class="block1 wrap-pic-w">
                    <img src="{{categorie.image.url}}" alt="IMG-BANNER">

                    <a href="{% url 'produits' %}" class="block1-txt ab-t-l s-full flex-col-l-sb p-lr-38 p-tb-34 trans-03 respon3">
                        <div class="block1-txt-child1 flex-col-l">
                            <span class="block1-name ltext-102 trans-04 p-b-8">
                                {{categorie.nom}}
                            </span>
                        </div>

                        <div class="block1-txt-child2 p-b-4 trans-05">
                            <div class="block1-link stext-101 cl0 trans-09">
                                Voir les produits
                            </div>
                        </div>
                    </a>
                </div>
            </div>

            {% endfor %}

        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

{% endblock %}

stage/templates/connexion.html
{% extends './layouts/base.html' %}
{% load static %}
{% block title %}
Connexion
{% endblock %}

{% block content %}
<!-- Title page -->
<section class="bg-img1 txt-center p-lr-15 p-tb-92" style="background-image: url({% static 'images/bg-01.jpg' %});">
    <h2 class="ltext-105 cl0 txt-center">
        Connexion
    </h2>
</section>
<!-- Content page -->
<section class="bg0 p-t-104 p-b-116">
    <div class="container">
        <div class="flex-w flex-tr w-100">
            <div class="size-210 bor10 p-lr-70 p-t-55 p-b-70 p-lr-15-lg w-full-md col-12">
                <form method="POST" action="{% url 'AuthGateway:validerconnexion' %}">
                    {% csrf_token %}
                    <h4 class="mtext-105 cl2 txt-center p-b-30">
                        Connectez-vous à votre compte
                    </h4>

                    <div class="bor8 m-b-20 how-pos4-parent">
                        <input class="stext-111 cl2 plh3 size-116 p-l-62 p-r-30" type="email" name="pseudo"
                            placeholder="Courriel" required>
                        <img class="how-pos4 pointer-none" src="{% static 'images/icons/icon-email.png' %}" alt="ICON">
                    </div>

                    <div class="bor8 m-b-20 how-pos4-parent">
                        <input class="stext-111 cl2 plh3 size-116 p-l-62 p-r-30" type="password" name="mdp"
                            placeholder="Mot de passe" , required>
                    </div>

                    <button class="flex-c-m stext-101 cl0 size-121 bg3 bor1 hov-btn3 p-lr-15 trans-04 pointer">
                        Se Connecter
                    </button>
                </form>
            </div>
        </div>
    </div>
</section>



{% endblock %}

{% block scripts %}
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

{% endblock %}

stage/templates/contact.html
{% extends './layouts/base.html' %}
{% load static %}
{% block title %}
Contact
{% endblock %}

{% block content %}
<!-- Title page -->
<section class="bg-img1 txt-center p-lr-15 p-tb-92" style="background-image: url({% static 'images/bg-01.jpg' %});">
    <h2 class="ltext-105 cl0 txt-center">
        Contact
    </h2>
</section>
<!-- Content page -->
<section class="bg0 p-t-104 p-b-116">
    <div class="container">
        <div class="flex-w flex-tr">
            <div class="size-210 bor10 p-lr-70 p-t-55 p-b-70 p-lr-15-lg w-full-md">
                <form>
                    <h4 class="mtext-105 cl2 txt-center p-b-30">
                        Envoyez Nous Un Message
                    </h4>

                    <div class="bor8 m-b-20 how-pos4-parent">
                        <input class="stext-111 cl2 plh3 size-116 p-l-62 p-r-30" type="text" name="email" placeholder="Ton Adresse E_mail">
                        <img class="how-pos4 pointer-none" src="{% static "images/icons/icon-email.png" %}" alt="ICON">
                    </div>

                    <div class="bor8 m-b-30">
                        <textarea class="stext-111 cl2 plh3 size-120 p-lr-28 p-tb-25" name="msg" placeholder="Comment puis-je t'aider?"></textarea>
                    </div>

                    <button class="flex-c-m stext-101 cl0 size-121 bg3 bor1 hov-btn3 p-lr-15 trans-04 pointer">
                        Envoyez
                    </button>
                </form>
            </div>

            <div class="size-210 bor10 flex-w flex-col-m p-lr-93 p-tb-30 p-lr-15-lg w-full-md">
                <div class="flex-w w-full p-b-42">
                    <span class="fs-18 cl5 txt-center size-211">
                        <span class="lnr lnr-map-marker"></span>
                    </span>

                    <div class="size-212 p-t-2">
                        <span class="mtext-110 cl2">
                            Adresse
                        </span>

                        <p class="stext-115 cl6 size-213 p-t-18">
                            L&H Store Center 3835 rue Paul Bourget
                        </p>
                    </div>
                </div>

                <div class="flex-w w-full p-b-42">
                    <span class="fs-18 cl5 txt-center size-211">
                        <span class="lnr lnr-phone-handset"></span>
                    </span>

                    <div class="size-212 p-t-2">
                        <span class="mtext-110 cl2">
                            Discutons
                        </span>

                        <p class="stext-115 cl1 size-213 p-t-18">
                            +1 438 4628246
                        </p>
                    </div>
                </div>

                <div class="flex-w w-full">
                    <span class="fs-18 cl5 txt-center size-211">
                        <span class="lnr lnr-envelope"></span>
                    </span>

                    <div class="size-212 p-t-2">
                        <span class="mtext-110 cl2">
                             Support
                        </span>

                        <p class="stext-115 cl1 size-213 p-t-18">
                            ashounalau@gmail.com
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>	

{% endblock %}

{% block scripts %}
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

{% endblock %}

stage/templates/index.html
{% extends './layouts/base.html' %}
{% load static %}

{% block title %}
Acceuil
{% endblock %}

{% block content %}

<div class="container mt-2">
    

    
</div>

	<!-- Slider -->
	<section class="section-slide">
		<div class="wrap-slick1">
			<div class="slick1">
				<div class="item-slick1" style="background-image: url({% static 'images/slide-01.jpg' %});">
					<div class="container h-full">
						<div class="flex-col-l-m h-full p-t-100 p-b-30 respon5">
							<div class="layer-slick1 animated visible-false" data-appear="fadeInDown" data-delay="0">
								<span class="ltext-101 cl2 respon2">
									 Collection Femme
								</span>
							</div>
								
							<div class="layer-slick1 animated visible-false" data-appear="fadeInUp" data-delay="800">
								<h2 class="ltext-201 cl2 p-t-19 p-b-43 respon1">
									NOUVELLE SAISON
								</h2>
							</div>
								
							<div class="layer-slick1 animated visible-false" data-appear="zoomIn" data-delay="1600">
								<a href="{% url 'produits' %}" class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04">
									Magazinez maintenant
								</a>
							</div>
						</div>
					</div>
				</div>

				<div class="item-slick1" style="background-image: url({% static 'images/slide-02.jpg' %});">
					<div class="container h-full">
						<div class="flex-col-l-m h-full p-t-100 p-b-30 respon5">
							<div class="layer-slick1 animated visible-false" data-appear="rollIn" data-delay="0">
								<span class="ltext-101 cl2 respon2">
                                    Collection Homme
								</span>
							</div>
								
							<div class="layer-slick1 animated visible-false" data-appear="lightSpeedIn" data-delay="800">
								<h2 class="ltext-201 cl2 p-t-19 p-b-43 respon1">
									Vestes & Pantalons
								</h2>
							</div>
								
							<div class="layer-slick1 animated visible-false" data-appear="slideInUp" data-delay="1600">
								<a href="{% url 'produits' %}" class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04">
									Magazinez maintenant
								</a>
							</div>
						</div>
					</div>
				</div>

				<div class="item-slick1" style="background-image: url({% static 'images/slide-03.jpg)' %};">
					<div class="container h-full">
						<div class="flex-col-l-m h-full p-t-100 p-b-30 respon5">
							<div class="layer-slick1 animated visible-false" data-appear="rotateInDownLeft" data-delay="0">
								<span class="ltext-101 cl2 respon2">
								   Collection Mixtes
								</span>
							</div>
								
							<div class="layer-slick1 animated visible-false" data-appear="rotateInUpRight" data-delay="800">
								<h2 class="ltext-201 cl2 p-t-19 p-b-43 respon1">
									Nouveautés
								</h2>
							</div>
								
							<div class="layer-slick1 animated visible-false" data-appear="rotateIn" data-delay="1600">
								<a href="{% url 'produits' %}" class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04">
									Magazinez maintenant
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

{% endblock %}

{% block scripts %}
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

{% endblock %}

stage/templates/inscription.html
{% extends './layouts/base.html' %}
{% load static %}
{% block title %}
Inscription
{% endblock %}

{% block content %}
<!-- Title page -->
<section class="bg-img1 txt-center p-lr-15 p-tb-92" style="background-image: url({% static 'images/bg-01.jpg' %});">
    <h2 class="ltext-105 cl0 txt-center">
        Inscription
    </h2>
</section>
<!-- Content page -->
<section class="bg0 p-t-104 p-b-116">
    <div class="container">
        <div class="flex-w flex-tr w-100">
            <div class="size-210 bor10 p-lr-70 p-t-55 p-b-70 p-lr-15-lg w-full-md col-12">
                <form method="POST" action="{% url 'AuthGateway:validerinscription' %}">
                    {% csrf_token %}
                    <h4 class="mtext-105 cl2 txt-center p-b-30">
                        Créer votre Compte
                    </h4>

                    <div class="bor8 m-b-20 how-pos4-parent">
                        <input class="stext-111 cl2 plh3 size-116 p-l-62 p-r-30" type="texte" name="nom"
                            placeholder="Nom" required>
                    </div>
                    <div class="bor8 m-b-20 how-pos4-parent">
                        <input class="stext-111 cl2 plh3 size-116 p-l-62 p-r-30" type="texte" name="prenom"
                            placeholder="Prenom" required>
                    </div>
                    <div class="bor8 m-b-20 how-pos4-parent">
                        <input class="stext-111 cl2 plh3 size-116 p-l-62 p-r-30" type="texte" name="adresse"
                            placeholder="Adresse" required>
                    </div>
                    <div class="bor8 m-b-20 how-pos4-parent">
                        <input class="stext-111 cl2 plh3 size-116 p-l-62 p-r-30" type="email" name="pseudo"
                            placeholder="Courriel" required>
                        <img class="how-pos4 pointer-none" src="{% static 'images/icons/icon-email.png' %}" alt="ICON">
                    </div>

                    <div class="bor8 m-b-20 how-pos4-parent">
                        <input class="stext-111 cl2 plh3 size-116 p-l-62 p-r-30" type="password" name="mdp"
                            placeholder="Mot de passe" , required>
                    </div>

                    <button class="flex-c-m stext-101 cl0 size-121 bg3 bor1 hov-btn3 p-lr-15 trans-04 pointer">
                        S'Insccrire
                    </button>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}

{% block scripts %}
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

{% endblock %}

stage/templates/paiementannuler.html
{% extends './layouts/base.html' %}
{% load static %}
{% block title %}
Paiementannulé
{% endblock %}

{% block content %}
<!-- Title page -->
<section class="bg-img1 txt-center p-lr-15 p-tb-92" style="background-image: url({% static 'images/bg-01.jpg' %});">
    <h2 class="ltext-105 cl0 txt-center">
        Votre paiement a été annulé avec succes
    </h2>
</section>
<!-- Content page -->



{% endblock %}

{% block scripts %}
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

{% endblock %}

stage/templates/paiementeffectuer.html
{% extends './layouts/base.html' %}
{% load static %}
{% block title %}
Paiement Effectué
{% endblock %}

{% block content %}
<!-- Title page -->
<section class="bg-img1 txt-center p-lr-15 p-tb-92" style="background-image: url({% static 'images/bg-01.jpg' %});">
    <h2 class="ltext-105 cl0 txt-center">
        Votre paiement a été effectué avec succes
    </h2>
</section>
<!-- Content page -->



{% endblock %}

{% block scripts %}
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

{% endblock %}

stage/templates/panier.html
{% extends './layouts/base.html' %}
{% load static %}
{% block title %}
Panier
{% endblock %}

{% block content %}
<!-- Title page -->
<section class="bg-img1 txt-center p-lr-15 p-tb-92" style="background-image: url({% static 'images/bg-01.jpg' %});">
    <h2 class="ltext-105 cl0 txt-center">
        Votre Panier
    </h2>
</section>
<!-- Content page -->
<form class="bg0 p-t-75 p-b-85" action="{% url 'procederpaiement' %}" method="POST">
    {% csrf_token %}
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-xl-7 m-lr-auto m-b-50">
                <div class="m-l-25 m-r--38 m-lr-0-xl">
                    <div class="wrap-table-shopping-cart">
                        <table class="table-shopping-cart">
                            <tr class="table_head">
                                <th class="column-1">Produit</th>
                                <th class="column-2"></th>
                                <th class="column-3">Prix</th>
                                <th class="column-4">Quantité</th>
                                <th class="column-5">Prix Total</th>
                            </tr>

                            {% for produitpanier in produitspanier %}
                            <tr class="table_row">
                                <td class="column-1">
                                    <div class="how-itemcart1">
                                        <img src="{{produitpanier.produit.image_principal.url}}" alt="IMG">
                                    </div>
                                </td>
                                <td class="column-2">{{produitpanier.produit.nom}}</td>
                                <td class="column-3">$CAD {{produitpanier.prix}}</td>
                                <td class="column-4"> {{produitpanier.quantiteSouhaite}}</td>
                                <td class="column-5">$CAD {{produitpanier.prixTotal}}</td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td class="text-center py-3" colspan="5">
                                    Votre panier est actuellement vide
                                </td>

                            </tr>
                            {% endfor %}

                        </table>
                    </div>

                    <div class="flex-w flex-sb-m bor15 p-t-18 p-b-15 p-lr-40 p-lr-15-sm">
                        <div
                            class="flex-c-m stext-101 cl2 size-119 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer m-tb-10">
                            <a href="{% url 'viderpanier' %}" class="text-dark">Vider le Panier</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-sm-10 col-lg-7 col-xl-5 m-lr-auto m-b-50">
                <div class="bor10 p-lr-40 p-t-30 p-b-40 m-l-63 m-r-40 m-lr-0-xl p-lr-15-sm">
                    <h4 class="mtext-109 cl2 p-b-30">
                        Total du Panier
                    </h4>

                    <div class="flex-w flex-t">
                        <div class="size-208">
                            <span class="mtext-101 cl2">
                                Prix Total:
                            </span>
                        </div>

                        <div class="size-209 p-t-1">
                            <span class="mtext-110 cl2">
                                $CAD {{prixTotal}}
                            </span>
                        </div>
                    </div>

                    <div class="flex-w flex-t bor12 p-t-15 p-b-30">
                        <div class="size-208 w-full-ssm">
                            <span class="stext-110 cl2">
                                Livraison:
                            </span>
                        </div>
                        <div class="bor8 bg0 m-b-22">
                            <input class="stext-111 cl8 plh3 size-111 p-lr-15" type="text" name="adresse_livraison"
                                placeholder="Adresse complete" required>
                        </div>

                    </div>

                    <button class="flex-c-m stext-101 cl0 size-116 bg3 bor14 hov-btn3 p-lr-15 trans-04 pointer"
                        type="submit">
                        Procéder au Payment
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>



{% endblock %}

{% block scripts %}
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

{% endblock %}

stage/templates/produits.html
{% extends './layouts/base.html' %}
{% load static %}
{% block title %}
Produits
{% endblock %}

{% block content %}
<!-- Title page -->
<section class="bg-img1 txt-center p-lr-15 p-tb-92" style="background-image: url({% static 'images/bg-01.jpg' %});">
    <h2 class="ltext-105 cl0 txt-center">
        Liste De Tous Les Produits de la boutique
    </h2>
</section>


	<!-- Product -->
	<section class="bg0 p-t-23 p-b-140">
		<div class="container">

			<div class="flex-w flex-sb-m p-b-52">
				<div class="flex-w flex-l-m filter-tope-group m-tb-10">
					<button class="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5 how-active1" data-filter="*">
						Tous les produits
					</button>

                    {% for categorie in categories %}
                    <button class="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5" data-filter=".{{categorie.nom}}">
						{{categorie.nom}}
					</button>
                    {% endfor %}
				</div>

			</div>

			<div class="row isotope-grid">
                {% for produit in produits %}
                <div class="col-sm-6 col-md-4 col-lg-3 p-b-35 isotope-item {{produit.categorie.nom}}">
					<div class="block2">
						<div class="block2-pic hov-img0">
							<img src="{{produit.image_principal.url}}" alt="IMG-PRODUCT">
						</div>

						<div class="block2-txt flex-w flex-t p-t-14">
							<div class="block2-txt-child1 flex-col-l ">
								<a href="{% url 'produit-detail' id=produit.pk %}" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
									{{produit.nom}}
								</a>

								<span class="stext-105 cl3">
									$CAD {{produit.prix}}
								</span>
							</div>

						</div>
					</div>
				</div>
                {% endfor %}

			</div>
		</div>
	</section>

{% endblock %}

{% block scripts %}
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

{% endblock %}